[manager]
prepend_keymap = [
  { on = "h", run = "leave", desc = "move left" },
  { on = "j", run = "arrow next", desc = "move down" },
  { on = "k", run = "arrow prev", desc = "move up" },
  { on = "l", run = "enter", desc = "move right" },
]
